### ISSUE TITLE
Database information required

### ISSUE THREAD

**Issue by temal32** [Krish-Panchani/SendBox-Chat#1]
Hello, you forgot to share the database information (.sql file) which includes the setup for the database (tables, rows, etc..).
Could you please add the setup sql file to the repo so I can add it to my database to use this chat application?

**Comment by Krish-Panchani** [comment]
Sure. I will upload it by today.

**Comment by temal32** [comment]
Ok, thanks. Please reply as soon as you've uploaded it!

**Comment by temal32** [comment]
Ok, thanks. Please reply as soon as you've uploaded it!

**Comment by temal32** [comment]
Ok, thanks. Please reply as soon as you've uploaded it!

**Comment by Krish-Panchani** [comment]
Hey @temal32,
I uploaded Database folder where you can find SQL files.
Sorry for late.

**Comment by temal32** [comment]
Hello @Krish-Panchani,
thanks, this issue is solved now.
Greetings Temal.
