### ISSUE TITLE
Several JavasScript Error when sending a message

### ISSUE THREAD

**Issue by temal32** [Krish-Panchani/SendBox-Chat#2]
Hello @Krish-Panchani,
I've prepared everything (set up database and upload website files).
But whenever I try to send a message it just does not work, the "send" button doesn't give any reaction and in the console I get two errors (first one without even sending a message, and the second if I try to send a message): 1. ```chat.js:64 Uncaught DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.```
2. ```chat.js:33 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.
    at sendBtn.onclick```
Could you please provide some help?
Greetings, Temal.

**Comment by Krish-Panchani** [comment]
Hey @temal32,
Thanks for informing me about this issue. 
I will look further about it and try to Solve it as soon as possible.

Mean while you have wait 1 - 2 days more untill I find the solution for It, Also if you have the better solution then you can create pull request about it. 

Thankyou

**Comment by temal32** [comment]
Alright, thank you. I'll wait.

**Comment by Krish-Panchani** [comment]
Hey @temal32, 
Just solved that issue which you are facing.
Made some changes in `javascript/chat.js` file.
Update that changes in your file then you are good go. 👍

Also let me know if you face any other errors or issues in future. I'm still happy to work on this project.

**Comment by temal32** [comment]
Hello @Krish-Panchani,
thank you, I've downloaded the new file and it works now!
What about the license? Am I free to use these files for my private website? Do I have to link you (credits)?
Greetings, Temal.

**Comment by Krish-Panchani** [comment]
> Hello @Krish-Panchani,
> thank you, I've downloaded the new file and it works now!
> What about the license? Am I free to use these files for my private website? Do I have to link you (credits)?
> Greetings, Temal.

Yes, you can use this chat in your website. And also it's helpful for me if you add credits.

**Comment by temal32** [comment]
Alright, everything is clear now.
